// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DentaloreChat.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260817093456_SeedClinicBGroup")]
    partial class SeedClinicBGroup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.29");

            modelBuilder.Entity("Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clinics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dental Clinic - Branch A"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dental Clinic - Branch B"
                        });
                });

            modelBuilder.Entity("Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClinicId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Conversations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClinicId = 1,
                            IsGroup = false
                        },
                        new
                        {
                            Id = 101,
                            ClinicId = 1,
                            GroupName = "Group Chat",
                            IsGroup = true
                        },
                        new
                        {
                            Id = 4,
                            ClinicId = 2,
                            IsGroup = false
                        },
                        new
                        {
                            Id = 102,
                            ClinicId = 2,
                            GroupName = "Clinic B Group Chat",
                            IsGroup = true
                        });
                });

            modelBuilder.Entity("ConversationMember", b =>
                {
                    b.Property<int>("ConversationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConversationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ConversationMembers");

                    b.HasData(
                        new
                        {
                            ConversationId = 1,
                            UserId = 1
                        },
                        new
                        {
                            ConversationId = 1,
                            UserId = 2
                        },
                        new
                        {
                            ConversationId = 101,
                            UserId = 1
                        },
                        new
                        {
                            ConversationId = 101,
                            UserId = 2
                        },
                        new
                        {
                            ConversationId = 4,
                            UserId = 3
                        },
                        new
                        {
                            ConversationId = 4,
                            UserId = 4
                        },
                        new
                        {
                            ConversationId = 102,
                            UserId = 3
                        },
                        new
                        {
                            ConversationId = 102,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConversationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SenderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Hello Dr. Ahmed, welcome to Dentalore!",
                            ConversationId = 1,
                            SenderId = 1,
                            Timestamp = new DateTime(2026, 8, 17, 9, 24, 55, 498, DateTimeKind.Utc).AddTicks(7176)
                        },
                        new
                        {
                            Id = 2,
                            Content = "Hi Dr. Hana! Ready to discuss today's clinic schedule.",
                            ConversationId = 1,
                            SenderId = 2,
                            Timestamp = new DateTime(2026, 8, 17, 9, 29, 55, 498, DateTimeKind.Utc).AddTicks(7184)
                        },
                        new
                        {
                            Id = 7,
                            Content = "Welcome doctors to our Branch A Team Group Chat! 👋",
                            ConversationId = 101,
                            SenderId = 1,
                            Timestamp = new DateTime(2026, 8, 17, 9, 9, 55, 498, DateTimeKind.Utc).AddTicks(7186)
                        },
                        new
                        {
                            Id = 8,
                            Content = "Great to have a shared channel!",
                            ConversationId = 101,
                            SenderId = 2,
                            Timestamp = new DateTime(2026, 8, 17, 9, 14, 55, 498, DateTimeKind.Utc).AddTicks(7187)
                        },
                        new
                        {
                            Id = 10,
                            Content = "Hi Dr. Sara, checking in from Branch B!",
                            ConversationId = 4,
                            SenderId = 4,
                            Timestamp = new DateTime(2026, 8, 17, 9, 32, 55, 498, DateTimeKind.Utc).AddTicks(7189)
                        },
                        new
                        {
                            Id = 201,
                            Content = "Welcome to Branch B group chat!",
                            ConversationId = 102,
                            SenderId = 3,
                            Timestamp = new DateTime(2026, 8, 17, 9, 24, 55, 498, DateTimeKind.Utc).AddTicks(7191)
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClinicId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClinicId = 1,
                            Name = "Dr. Hana"
                        },
                        new
                        {
                            Id = 2,
                            ClinicId = 1,
                            Name = "Dr. Ahmed"
                        },
                        new
                        {
                            Id = 3,
                            ClinicId = 2,
                            Name = "Dr. Sara"
                        },
                        new
                        {
                            Id = 4,
                            ClinicId = 2,
                            Name = "Dr. Omar"
                        });
                });

            modelBuilder.Entity("ConversationMember", b =>
                {
                    b.HasOne("Conversation", "Conversation")
                        .WithMany("Members")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Message", b =>
                {
                    b.HasOne("Conversation", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("Clinic", "Clinic")
                        .WithMany("Users")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("Clinic", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Conversation", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
