// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DentaloreChat.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811170142_AddAllConversationsAndMessages")]
    partial class AddAllConversationsAndMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.29");

            modelBuilder.Entity("Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clinics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dental Clinic - Branch A"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dental Clinic - Branch B"
                        });
                });

            modelBuilder.Entity("Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClinicId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Conversations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClinicId = 1,
                            IsGroup = false
                        },
                        new
                        {
                            Id = 2,
                            ClinicId = 1,
                            IsGroup = false
                        },
                        new
                        {
                            Id = 3,
                            ClinicId = 1,
                            IsGroup = false
                        },
                        new
                        {
                            Id = 101,
                            ClinicId = 1,
                            GroupName = "Group Chat",
                            IsGroup = true
                        });
                });

            modelBuilder.Entity("ConversationMember", b =>
                {
                    b.Property<int>("ConversationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConversationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ConversationMembers");

                    b.HasData(
                        new
                        {
                            ConversationId = 1,
                            UserId = 1
                        },
                        new
                        {
                            ConversationId = 1,
                            UserId = 2
                        },
                        new
                        {
                            ConversationId = 2,
                            UserId = 1
                        },
                        new
                        {
                            ConversationId = 2,
                            UserId = 3
                        },
                        new
                        {
                            ConversationId = 3,
                            UserId = 2
                        },
                        new
                        {
                            ConversationId = 3,
                            UserId = 3
                        },
                        new
                        {
                            ConversationId = 101,
                            UserId = 1
                        },
                        new
                        {
                            ConversationId = 101,
                            UserId = 2
                        },
                        new
                        {
                            ConversationId = 101,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConversationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SenderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Hello Dr. Ahmed, welcome to Dentalore!",
                            ConversationId = 1,
                            SenderId = 1,
                            Timestamp = new DateTime(2026, 8, 11, 16, 51, 41, 512, DateTimeKind.Utc).AddTicks(4721)
                        },
                        new
                        {
                            Id = 2,
                            Content = "Hi Dr. Malak! Ready to discuss today's clinic schedule.",
                            ConversationId = 1,
                            SenderId = 2,
                            Timestamp = new DateTime(2026, 8, 11, 16, 56, 41, 512, DateTimeKind.Utc).AddTicks(4730)
                        },
                        new
                        {
                            Id = 3,
                            Content = "Hi Dr. Sara! How is Branch B operations today?",
                            ConversationId = 2,
                            SenderId = 1,
                            Timestamp = new DateTime(2026, 8, 11, 16, 49, 41, 512, DateTimeKind.Utc).AddTicks(4732)
                        },
                        new
                        {
                            Id = 4,
                            Content = "Hello Dr. Malak! Everything is running smoothly at Branch B.",
                            ConversationId = 2,
                            SenderId = 3,
                            Timestamp = new DateTime(2026, 8, 11, 16, 54, 41, 512, DateTimeKind.Utc).AddTicks(4734)
                        },
                        new
                        {
                            Id = 5,
                            Content = "Hi Dr. Sara, checking in from Branch A.",
                            ConversationId = 3,
                            SenderId = 2,
                            Timestamp = new DateTime(2026, 8, 11, 16, 53, 41, 512, DateTimeKind.Utc).AddTicks(4735)
                        },
                        new
                        {
                            Id = 6,
                            Content = "Hi Dr. Ahmed! Patient cases are updated.",
                            ConversationId = 3,
                            SenderId = 3,
                            Timestamp = new DateTime(2026, 8, 11, 16, 57, 41, 512, DateTimeKind.Utc).AddTicks(4737)
                        },
                        new
                        {
                            Id = 7,
                            Content = "Welcome doctors to our Dental Clinic Team Group Chat! 👋",
                            ConversationId = 101,
                            SenderId = 1,
                            Timestamp = new DateTime(2026, 8, 11, 16, 36, 41, 512, DateTimeKind.Utc).AddTicks(4739)
                        },
                        new
                        {
                            Id = 8,
                            Content = "Great to have a shared channel for Branch A and Branch B!",
                            ConversationId = 101,
                            SenderId = 2,
                            Timestamp = new DateTime(2026, 8, 11, 16, 41, 41, 512, DateTimeKind.Utc).AddTicks(4740)
                        },
                        new
                        {
                            Id = 9,
                            Content = "Dr. Sara joining from Branch B! Ready to collaborate.",
                            ConversationId = 101,
                            SenderId = 3,
                            Timestamp = new DateTime(2026, 8, 11, 16, 46, 41, 512, DateTimeKind.Utc).AddTicks(4742)
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClinicId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClinicId = 1,
                            Name = "Dr. Malak"
                        },
                        new
                        {
                            Id = 2,
                            ClinicId = 1,
                            Name = "Dr. Ahmed"
                        },
                        new
                        {
                            Id = 3,
                            ClinicId = 2,
                            Name = "Dr. Sara"
                        });
                });

            modelBuilder.Entity("ConversationMember", b =>
                {
                    b.HasOne("Conversation", "Conversation")
                        .WithMany("Members")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Message", b =>
                {
                    b.HasOne("Conversation", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("Clinic", "Clinic")
                        .WithMany("Users")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("Clinic", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Conversation", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
