// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DentaloreChat.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.29");

            modelBuilder.Entity("Clinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clinics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Dental Clinic - Branch A"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Dental Clinic - Branch B"
                        });
                });

            modelBuilder.Entity("Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Conversations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111111"),
                            ClinicId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsGroup = false
                        },
                        new
                        {
                            Id = new Guid("c1010101-1111-1111-1111-111111111111"),
                            ClinicId = new Guid("11111111-1111-1111-1111-111111111111"),
                            GroupName = "Group Chat",
                            IsGroup = true
                        },
                        new
                        {
                            Id = new Guid("c4444444-4444-4444-4444-444444444444"),
                            ClinicId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsGroup = false
                        },
                        new
                        {
                            Id = new Guid("c1020202-2222-2222-2222-222222222222"),
                            ClinicId = new Guid("22222222-2222-2222-2222-222222222222"),
                            GroupName = "Clinic B Group Chat",
                            IsGroup = true
                        });
                });

            modelBuilder.Entity("ConversationMember", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("ConversationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ConversationMembers");

                    b.HasData(
                        new
                        {
                            ConversationId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("a1111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ConversationId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("a2222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            ConversationId = new Guid("c1010101-1111-1111-1111-111111111111"),
                            UserId = new Guid("a1111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ConversationId = new Guid("c1010101-1111-1111-1111-111111111111"),
                            UserId = new Guid("a2222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            ConversationId = new Guid("c4444444-4444-4444-4444-444444444444"),
                            UserId = new Guid("a3333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            ConversationId = new Guid("c4444444-4444-4444-4444-444444444444"),
                            UserId = new Guid("a4444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            ConversationId = new Guid("c1020202-2222-2222-2222-222222222222"),
                            UserId = new Guid("a3333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            ConversationId = new Guid("c1020202-2222-2222-2222-222222222222"),
                            UserId = new Guid("a4444444-4444-4444-4444-444444444444")
                        });
                });

            modelBuilder.Entity("Message", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Content = "Hello Dr. Ahmed, welcome to Dentalore!",
                            ConversationId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            SenderId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Timestamp = new DateTime(2026, 8, 18, 12, 40, 44, 438, DateTimeKind.Utc).AddTicks(6809)
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            Content = "Hi Dr. Hana! Ready to discuss today's clinic schedule.",
                            ConversationId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            SenderId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            Timestamp = new DateTime(2026, 8, 18, 12, 45, 44, 438, DateTimeKind.Utc).AddTicks(6816)
                        },
                        new
                        {
                            Id = new Guid("b7777777-7777-7777-7777-777777777777"),
                            Content = "Welcome doctors to our Branch A Team Group Chat! 👋",
                            ConversationId = new Guid("c1010101-1111-1111-1111-111111111111"),
                            SenderId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Timestamp = new DateTime(2026, 8, 18, 12, 25, 44, 438, DateTimeKind.Utc).AddTicks(6818)
                        },
                        new
                        {
                            Id = new Guid("b8888888-8888-8888-8888-888888888888"),
                            Content = "Great to have a shared channel!",
                            ConversationId = new Guid("c1010101-1111-1111-1111-111111111111"),
                            SenderId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            Timestamp = new DateTime(2026, 8, 18, 12, 30, 44, 438, DateTimeKind.Utc).AddTicks(6820)
                        },
                        new
                        {
                            Id = new Guid("b1010101-0000-0000-0000-000000000000"),
                            Content = "Hi Dr. Sara, checking in from Branch B!",
                            ConversationId = new Guid("c4444444-4444-4444-4444-444444444444"),
                            SenderId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            Timestamp = new DateTime(2026, 8, 18, 12, 48, 44, 438, DateTimeKind.Utc).AddTicks(6822)
                        },
                        new
                        {
                            Id = new Guid("b2010201-0000-0000-0000-000000000000"),
                            Content = "Welcome to Branch B group chat!",
                            ConversationId = new Guid("c1020202-2222-2222-2222-222222222222"),
                            SenderId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            Timestamp = new DateTime(2026, 8, 18, 12, 40, 44, 438, DateTimeKind.Utc).AddTicks(6823)
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClinicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            ClinicId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Dr. Hana"
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            ClinicId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Dr. Ahmed"
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            ClinicId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Dr. Sara"
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444444"),
                            ClinicId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Dr. Omar"
                        });
                });

            modelBuilder.Entity("ConversationMember", b =>
                {
                    b.HasOne("Conversation", "Conversation")
                        .WithMany("Members")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Message", b =>
                {
                    b.HasOne("Conversation", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("Clinic", "Clinic")
                        .WithMany("Users")
                        .HasForeignKey("ClinicId");

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("Clinic", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Conversation", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
