// <auto-generated />
using System;
using DentaloreChat.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DentaloreChat.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260820130843_AddMessageReactions")]
    partial class AddMessageReactions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DentaloreChat.Domain.Entities.Clinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clinics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Dental Clinic - Branch A"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Dental Clinic - Branch B"
                        });
                });

            modelBuilder.Entity("DentaloreChat.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<string>("GroupName")
                        .HasColumnType("text");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Conversations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111111"),
                            ClinicId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsGroup = false
                        },
                        new
                        {
                            Id = new Guid("c1010101-1111-1111-1111-111111111111"),
                            ClinicId = new Guid("11111111-1111-1111-1111-111111111111"),
                            GroupName = "Group Chat",
                            IsGroup = true
                        },
                        new
                        {
                            Id = new Guid("c4444444-4444-4444-4444-444444444444"),
                            ClinicId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsGroup = false
                        },
                        new
                        {
                            Id = new Guid("c1020202-2222-2222-2222-222222222222"),
                            ClinicId = new Guid("22222222-2222-2222-2222-222222222222"),
                            GroupName = "Clinic B Group Chat",
                            IsGroup = true
                        });
                });

            modelBuilder.Entity("DentaloreChat.Domain.Entities.ConversationMember", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ConversationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ConversationMembers");

                    b.HasData(
                        new
                        {
                            ConversationId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("a1111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ConversationId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("a2222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            ConversationId = new Guid("c1010101-1111-1111-1111-111111111111"),
                            UserId = new Guid("a1111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ConversationId = new Guid("c1010101-1111-1111-1111-111111111111"),
                            UserId = new Guid("a2222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            ConversationId = new Guid("c4444444-4444-4444-4444-444444444444"),
                            UserId = new Guid("a3333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            ConversationId = new Guid("c4444444-4444-4444-4444-444444444444"),
                            UserId = new Guid("a4444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            ConversationId = new Guid("c1020202-2222-2222-2222-222222222222"),
                            UserId = new Guid("a3333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            ConversationId = new Guid("c1020202-2222-2222-2222-222222222222"),
                            UserId = new Guid("a4444444-4444-4444-4444-444444444444")
                        });
                });

            modelBuilder.Entity("DentaloreChat.Domain.Entities.Message", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Content = "Hello Dr. Ahmed, welcome to Dentalore!",
                            ConversationId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            SenderId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Timestamp = new DateTime(2026, 8, 20, 12, 58, 42, 170, DateTimeKind.Utc).AddTicks(4397)
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            Content = "Hi Dr. Hana! Ready to discuss today's clinic schedule.",
                            ConversationId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            SenderId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            Timestamp = new DateTime(2026, 8, 20, 13, 3, 42, 170, DateTimeKind.Utc).AddTicks(4408)
                        },
                        new
                        {
                            Id = new Guid("b7777777-7777-7777-7777-777777777777"),
                            Content = "Welcome doctors to our Branch A Team Group Chat! 👋",
                            ConversationId = new Guid("c1010101-1111-1111-1111-111111111111"),
                            SenderId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Timestamp = new DateTime(2026, 8, 20, 12, 43, 42, 170, DateTimeKind.Utc).AddTicks(4412)
                        },
                        new
                        {
                            Id = new Guid("b8888888-8888-8888-8888-888888888888"),
                            Content = "Great to have a shared channel!",
                            ConversationId = new Guid("c1010101-1111-1111-1111-111111111111"),
                            SenderId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            Timestamp = new DateTime(2026, 8, 20, 12, 48, 42, 170, DateTimeKind.Utc).AddTicks(4419)
                        },
                        new
                        {
                            Id = new Guid("b1010101-0000-0000-0000-000000000000"),
                            Content = "Hi Dr. Sara, checking in from Branch B!",
                            ConversationId = new Guid("c4444444-4444-4444-4444-444444444444"),
                            SenderId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            Timestamp = new DateTime(2026, 8, 20, 13, 6, 42, 170, DateTimeKind.Utc).AddTicks(4423)
                        },
                        new
                        {
                            Id = new Guid("b2010201-0000-0000-0000-000000000000"),
                            Content = "Welcome to Branch B group chat!",
                            ConversationId = new Guid("c1020202-2222-2222-2222-222222222222"),
                            SenderId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            Timestamp = new DateTime(2026, 8, 20, 12, 58, 42, 170, DateTimeKind.Utc).AddTicks(4427)
                        });
                });

            modelBuilder.Entity("DentaloreChat.Domain.Entities.Reaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("UserId");

                    b.ToTable("Reactions");
                });

            modelBuilder.Entity("DentaloreChat.Domain.Entities.User", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClinicId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            ClinicId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Dr. Hana"
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            ClinicId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Dr. Ahmed"
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            ClinicId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Dr. Sara"
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444444"),
                            ClinicId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Dr. Omar"
                        });
                });

            modelBuilder.Entity("DentaloreChat.Domain.Entities.ConversationMember", b =>
                {
                    b.HasOne("DentaloreChat.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Members")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DentaloreChat.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DentaloreChat.Domain.Entities.Message", b =>
                {
                    b.HasOne("DentaloreChat.Domain.Entities.Conversation", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DentaloreChat.Domain.Entities.Reaction", b =>
                {
                    b.HasOne("DentaloreChat.Domain.Entities.Message", "Message")
                        .WithMany("Reactions")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DentaloreChat.Domain.Entities.User", "User")
                        .WithMany("Reactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DentaloreChat.Domain.Entities.User", b =>
                {
                    b.HasOne("DentaloreChat.Domain.Entities.Clinic", "Clinic")
                        .WithMany("Users")
                        .HasForeignKey("ClinicId");

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("DentaloreChat.Domain.Entities.Clinic", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DentaloreChat.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("DentaloreChat.Domain.Entities.Message", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("DentaloreChat.Domain.Entities.User", b =>
                {
                    b.Navigation("Reactions");
                });
#pragma warning restore 612, 618
        }
    }
}
